services:
  service-a:
    build:
      context: ./service-a
    ports:
      - "8080:8080"
    depends_on:
      - envoy
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  service-b:
    build:
      context: ./service-b
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  envoy:
    image: envoyproxy/envoy:v1.26.0
    ports:
      - "9901:9901"
      - "9902:9902"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    depends_on:
      - service-b